
import { HistoryItem, SunoResult, InputMode } from '../types';

const STORAGE_KEY = 'suno_architect_history_v1';

export const saveToHistory = (result: SunoResult, inputMode: InputMode, inputText: string): HistoryItem => {
  const history = getHistory();
  
  const newItem: HistoryItem = {
    id: Date.now().toString(),
    timestamp: Date.now(),
    inputMode,
    inputSummary: inputMode === InputMode.AUDIO ? 'Audio Analysis' : (inputText.slice(0, 30) + (inputText.length > 30 ? '...' : '')),
    result
  };

  // Prepend to array (newest first)
  const updatedHistory = [newItem, ...history].slice(0, 50); // Limit to 50 items
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updatedHistory));
  return newItem;
};

export const getHistory = (): HistoryItem[] => {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch (e) {
    console.error("Failed to parse history", e);
    return [];
  }
};

export const deleteHistoryItem = (id: string): HistoryItem[] => {
  const history = getHistory();
  const updated = history.filter(item => item.id !== id);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  return updated;
};

export const clearHistory = () => {
  localStorage.removeItem(STORAGE_KEY);
};

export const generateSunoDocument = (item: HistoryItem): string => {
  const { result } = item;
  const mp = result.masterPrompt;
  const analysis = result.analysis;
  const date = new Date(item.timestamp).toLocaleString();

  return `
=========================================
 SUNO ARCHITECT V5 PROJECT DOCUMENT
 Created: ${date}
 ID: ${item.id}
=========================================

[PROJECT INFO]
Title: ${mp.title}
Input: ${item.inputSummary}
Core Genre: ${analysis.genre}
BPM: ${analysis.bpm} | Key: ${analysis.key}

-----------------------------------------
[MASTER STYLE PROMPT]
${mp.styleDescription}

-----------------------------------------
[LYRICS & STRUCTURE]
${mp.lyricsAndStructure}

-----------------------------------------
[ADVANCED SETTINGS]
Weirdness: ${mp.advancedSettings.weirdness}%
Style Influence: ${mp.advancedSettings.styleInfluence}%
Vocal Gender: ${mp.advancedSettings.vocalGender}

-----------------------------------------
[ANALYSIS METADATA]
Instruments: ${analysis.instruments.join(', ')}
Chords: ${analysis.chordProgression}
Vocal Texture: ${analysis.vocalTexture}

=========================================
 VARIANTS
=========================================

${result.variants.map(v => `
> ${v.name}: "${v.title}"
  Style Mod: ${v.styleAdjustment}
  Weirdness: ${v.advancedSettings.weirdness}%
`).join('\n')}

=========================================
 Generated by Suno Architect
=========================================
`.trim();
};
